# Generated by Django 3.2.25 on 2024-12-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0004_auto_20241216_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='list_ingredient',
            field=models.ManyToManyField(to='ingredient.IngredientItem'),
        ),
    ]
